apiVersion: v1
kind: PersistentVolumeClaim

metadata:
 name: webpvc2

spec: 
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment

metadata:
 name: httpserver
 labels:
   app: httpserver

spec:
 replicas: 3
 selector:
   matchLabels:
     app: httpserver
 strategy:
  type: Recreate

 template:
   metadata:
     labels:
       app: httpserver
   spec:
     containers:
     - name: httpimage
       image: httpd
       imagePullPolicy: Always
       ports:
       - containerPort: 80
       volumeMounts:
       - name: web1mount
         mountPath: /usr/local/apache2/htdocs
     volumes:
     - name: web1mount
       persistentVolumeClaim:
         claimName: webpvc2
---

apiVersion: v1
kind: Service
metadata:
  name: hostname-serv
spec:
  type: NodePort
  selector:
    app: httpserver
  ports:
    - nodePort: 30199
      port: 8787
      targetPort: 80    
